openapi: 3.0.1
info:
  title: CMS
  description: API Definition of CMS
  version: 1.0.0
servers:
- url: http://localhost:8290/cms
paths:
  /getOrders/{customerID}:
    get:
      parameters:
      - name: customerID
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
