openapi: 3.0.1
info:
  title: Notifications
  description: API Definition of Notifications
  version: 1.0.0
servers:
- url: http://localhost:8290/notifications
paths:
  /:
    get:
      responses:
        default:
          description: Default response
