openapi: 3.0.1
info:
  title: packageDetails
  description: API Definition of packageDetails
  version: 1.0.0
servers:
- url: http://localhost:8290/packagedetails
paths:
  /:
    get:
      responses:
        default:
          description: Default response
